### ISSUE TITLE
MYSQL code not found

### ISSUE THREAD

**Issue by guepejuang** [starlut/Chat-App-on-Android#1]
can you upload the sql code so that I can import it in phpmyadmin?

**Comment by AdnanNazir** [comment]
Yes, If you could please provide with the db structure. Thanks

**Comment by khalid-hayat** [comment]
DB file is missing, I will be thank full if you push SQL file as well.

**Comment by sigky** [comment]
I will be thank full if you push SQL file as well.

**Comment by starlut** [comment]
i don't have the db file. i will try to recreate it and push it as well by tomorrow evening hopefully

**Comment by starlut** [comment]
db uploaded

**Comment by sigky** [comment]
Gracias hermano por tu code y tiempo
